### ISSUE TITLE
Announce plugin on mailing list?

### ISSUE THREAD

**Issue by thibaultcha** [b-rajesh/kong-schedule-outage-plugin#5]
Hello!

Good job on the plugin! I have definitely seen some members of the community asking for a scheduled outage plugin in the past! We are happy to see members of the community stepping forward and publishing Kong plugins on Luarocks :)

As of now, we don't offer you yet a way to advertise your plugin on https://getkong.org/plugins, but are planning to in the future. In the meantime, feel free to publish an announcement on the [Kong Mailing List](https://groups.google.com/forum/#!forum/konglayer), as I am sure it will give you some exposition and peak the interest of some Kong users out there.

```
[ANN] Community Plugin - kong-schedule-outage-plugin [plugin version]
```

Just a suggestion :)

Best,
Thibault

**Comment by b-rajesh** [comment]
Thank you Thibault, I was looking for an option to let know about this plugin. Will try the mailing list.

cheers
